### PR TITLE
#8 docs: Organize doc generate javadoc

### LINKED ISSUE #8: Organize documentation and generate javadoc

### PR DESCRIPTION
**Pull request by AdamJonsson**

### CODE REVIEW

**Comment by AdamJonsson** [comment]
@Autonymic Is this one ready for review?

**Comment by AdamJonsson** [comment]
@Autonymic @LaraRos  @isakvi  Can someone else review this? I can not as I was the one who created this PR

**Review by manjikian — COMMENTED** [review]
We have three undocumented classes. Should we add a short documentation comment on them?

**Review by isakvi — APPROVED** [review]
Looks good to me

**Pull request merged**
